package com.xhh.system.tj.matchoa.model;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_oa_limit.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_oa_limit.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_oa_limit.login_pwd
     *
     * @mbggenerated
     */
    private String loginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_oa_limit.login_limit_lv
     *
     * @mbggenerated
     */
    private String loginLimitLv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_oa_limit.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_oa_limit.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_oa_limit.lock_type
     *
     * @mbggenerated
     */
    private String lockType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_oa_limit.verification_code
     *
     * @mbggenerated
     */
    private String verificationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_oa_limit.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_oa_limit.surplus_login_num
     *
     * @mbggenerated
     */
    private String surplusLoginNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column match_oa_limit.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table match_oa_limit
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_oa_limit.id
     *
     * @return the value of match_oa_limit.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_oa_limit.id
     *
     * @param id the value for match_oa_limit.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_oa_limit.login_name
     *
     * @return the value of match_oa_limit.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_oa_limit.login_name
     *
     * @param loginName the value for match_oa_limit.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_oa_limit.login_pwd
     *
     * @return the value of match_oa_limit.login_pwd
     *
     * @mbggenerated
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_oa_limit.login_pwd
     *
     * @param loginPwd the value for match_oa_limit.login_pwd
     *
     * @mbggenerated
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_oa_limit.login_limit_lv
     *
     * @return the value of match_oa_limit.login_limit_lv
     *
     * @mbggenerated
     */
    public String getLoginLimitLv() {
        return loginLimitLv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_oa_limit.login_limit_lv
     *
     * @param loginLimitLv the value for match_oa_limit.login_limit_lv
     *
     * @mbggenerated
     */
    public void setLoginLimitLv(String loginLimitLv) {
        this.loginLimitLv = loginLimitLv == null ? null : loginLimitLv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_oa_limit.create_time
     *
     * @return the value of match_oa_limit.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_oa_limit.create_time
     *
     * @param createTime the value for match_oa_limit.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_oa_limit.modify_time
     *
     * @return the value of match_oa_limit.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_oa_limit.modify_time
     *
     * @param modifyTime the value for match_oa_limit.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_oa_limit.lock_type
     *
     * @return the value of match_oa_limit.lock_type
     *
     * @mbggenerated
     */
    public String getLockType() {
        return lockType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_oa_limit.lock_type
     *
     * @param lockType the value for match_oa_limit.lock_type
     *
     * @mbggenerated
     */
    public void setLockType(String lockType) {
        this.lockType = lockType == null ? null : lockType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_oa_limit.verification_code
     *
     * @return the value of match_oa_limit.verification_code
     *
     * @mbggenerated
     */
    public String getVerificationCode() {
        return verificationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_oa_limit.verification_code
     *
     * @param verificationCode the value for match_oa_limit.verification_code
     *
     * @mbggenerated
     */
    public void setVerificationCode(String verificationCode) {
        this.verificationCode = verificationCode == null ? null : verificationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_oa_limit.mobile
     *
     * @return the value of match_oa_limit.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_oa_limit.mobile
     *
     * @param mobile the value for match_oa_limit.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_oa_limit.surplus_login_num
     *
     * @return the value of match_oa_limit.surplus_login_num
     *
     * @mbggenerated
     */
    public String getSurplusLoginNum() {
        return surplusLoginNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_oa_limit.surplus_login_num
     *
     * @param surplusLoginNum the value for match_oa_limit.surplus_login_num
     *
     * @mbggenerated
     */
    public void setSurplusLoginNum(String surplusLoginNum) {
        this.surplusLoginNum = surplusLoginNum == null ? null : surplusLoginNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column match_oa_limit.token
     *
     * @return the value of match_oa_limit.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column match_oa_limit.token
     *
     * @param token the value for match_oa_limit.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_oa_limit
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getLoginName() == null ? other.getLoginName() == null : this.getLoginName().equals(other.getLoginName()))
            && (this.getLoginPwd() == null ? other.getLoginPwd() == null : this.getLoginPwd().equals(other.getLoginPwd()))
            && (this.getLoginLimitLv() == null ? other.getLoginLimitLv() == null : this.getLoginLimitLv().equals(other.getLoginLimitLv()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getModifyTime() == null ? other.getModifyTime() == null : this.getModifyTime().equals(other.getModifyTime()))
            && (this.getLockType() == null ? other.getLockType() == null : this.getLockType().equals(other.getLockType()))
            && (this.getVerificationCode() == null ? other.getVerificationCode() == null : this.getVerificationCode().equals(other.getVerificationCode()))
            && (this.getMobile() == null ? other.getMobile() == null : this.getMobile().equals(other.getMobile()))
            && (this.getSurplusLoginNum() == null ? other.getSurplusLoginNum() == null : this.getSurplusLoginNum().equals(other.getSurplusLoginNum()))
            && (this.getToken() == null ? other.getToken() == null : this.getToken().equals(other.getToken()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_oa_limit
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getLoginName() == null) ? 0 : getLoginName().hashCode());
        result = prime * result + ((getLoginPwd() == null) ? 0 : getLoginPwd().hashCode());
        result = prime * result + ((getLoginLimitLv() == null) ? 0 : getLoginLimitLv().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getModifyTime() == null) ? 0 : getModifyTime().hashCode());
        result = prime * result + ((getLockType() == null) ? 0 : getLockType().hashCode());
        result = prime * result + ((getVerificationCode() == null) ? 0 : getVerificationCode().hashCode());
        result = prime * result + ((getMobile() == null) ? 0 : getMobile().hashCode());
        result = prime * result + ((getSurplusLoginNum() == null) ? 0 : getSurplusLoginNum().hashCode());
        result = prime * result + ((getToken() == null) ? 0 : getToken().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table match_oa_limit
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", loginName=").append(loginName);
        sb.append(", loginPwd=").append(loginPwd);
        sb.append(", loginLimitLv=").append(loginLimitLv);
        sb.append(", createTime=").append(createTime);
        sb.append(", modifyTime=").append(modifyTime);
        sb.append(", lockType=").append(lockType);
        sb.append(", verificationCode=").append(verificationCode);
        sb.append(", mobile=").append(mobile);
        sb.append(", surplusLoginNum=").append(surplusLoginNum);
        sb.append(", token=").append(token);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}